### ISSUE TITLE
Error by building x11-drivers/nvidia-kernel-modules-418.56

### ISSUE THREAD

**Issue by CrawlerSpider** [TemptorSent/overlay-nvidia-kit#1]
* Messages for package x11-drivers/nvidia-kernel-modules-418.56:

 * Gentoo supports kernels which are supported by NVIDIA
 * which are limited to the following kernels:
 * <sys-kernel/gentoo-sources-4.17
 * <sys-kernel/vanilla-sources-4.17
 * 
 * You are free to utilize epatch_user to provide whatever
 * support you feel is appropriate, but will not receive
 * support as a result of those changes.
 * 
 * Do not file a bug report about this.
 * 
 * ERROR: x11-drivers/nvidia-kernel-modules-418.56::nvidia-kit failed (unpack phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  92:  Called src_unpack
 *   environment, line 4806:  Called die
 * The specific snippet of code:
 *       cp -r "${NVDRIVERS_DIR}/src/kernel-modules" "${S}" || die

**Comment by TemptorSent** [comment]
Warning was due to out of date kernel version check (updated in tree)
Error was due to modules attempting to install before the nvidia-drivers package which installs the sources. (fixed by adding dep)
